// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "acg_top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic acg_top::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> acg_top::ap_ST_fsm_state1 = "1";
const sc_lv<32> acg_top::ap_const_lv32_0 = "00000000000000000000000000000000";
const int acg_top::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> acg_top::ap_const_lv32_1 = "1";
const sc_lv<32> acg_top::ap_const_lv32_2 = "10";
const sc_lv<32> acg_top::ap_const_lv32_3 = "11";
const sc_lv<32> acg_top::ap_const_lv32_1F = "11111";
const sc_logic acg_top::ap_const_logic_0 = sc_dt::Log_0;
const bool acg_top::ap_const_boolean_1 = true;

acg_top::acg_top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    acg_top_AXILiteS_s_axi_U = new acg_top_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("acg_top_AXILiteS_s_axi_U");
    acg_top_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    acg_top_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    acg_top_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    acg_top_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    acg_top_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    acg_top_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    acg_top_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    acg_top_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    acg_top_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    acg_top_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    acg_top_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    acg_top_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    acg_top_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    acg_top_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    acg_top_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    acg_top_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    acg_top_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    acg_top_AXILiteS_s_axi_U->ACLK(ap_clk);
    acg_top_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    acg_top_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    acg_top_AXILiteS_s_axi_U->inc_V(inc_V);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_4_fu_144_p3 );
    sensitive << ( tmp_5_fu_152_p3 );
    sensitive << ( tmp_6_fu_160_p3 );
    sensitive << ( tmp_8_fu_168_p3 );
    sensitive << ( tmp_9_fu_176_p3 );
    sensitive << ( tmp_10_fu_184_p3 );
    sensitive << ( tmp_11_fu_192_p3 );
    sensitive << ( tmp_12_fu_200_p3 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_p_Val2_1_fu_126_p2);
    sensitive << ( accumulator_V_0 );
    sensitive << ( tmp_7_fu_62_p2 );

    SC_METHOD(thread_p_Val2_2_fu_120_p2);
    sensitive << ( accumulator_V_0 );
    sensitive << ( tmp2_fu_114_p2 );

    SC_METHOD(thread_p_Val2_3_fu_78_p2);
    sensitive << ( accumulator_V_0 );
    sensitive << ( r_V_fu_44_p2 );

    SC_METHOD(thread_p_Val2_4_fu_108_p2);
    sensitive << ( accumulator_V_0 );
    sensitive << ( tmp1_fu_102_p2 );

    SC_METHOD(thread_p_Val2_5_fu_90_p2);
    sensitive << ( accumulator_V_0 );
    sensitive << ( tmp_fu_84_p2 );

    SC_METHOD(thread_p_Val2_6_fu_96_p2);
    sensitive << ( accumulator_V_0 );
    sensitive << ( r_V_1_fu_50_p2 );

    SC_METHOD(thread_p_Val2_7_fu_72_p2);
    sensitive << ( inc_V );
    sensitive << ( accumulator_V_0 );

    SC_METHOD(thread_p_Val2_s_fu_132_p2);
    sensitive << ( accumulator_V_0 );
    sensitive << ( r_V_2_fu_56_p2 );

    SC_METHOD(thread_r_V_1_fu_50_p2);
    sensitive << ( inc_V );

    SC_METHOD(thread_r_V_2_fu_56_p2);
    sensitive << ( inc_V );

    SC_METHOD(thread_r_V_fu_44_p2);
    sensitive << ( inc_V );

    SC_METHOD(thread_tmp1_fu_102_p2);
    sensitive << ( inc_V );
    sensitive << ( r_V_1_fu_50_p2 );

    SC_METHOD(thread_tmp2_fu_114_p2);
    sensitive << ( r_V_fu_44_p2 );
    sensitive << ( r_V_1_fu_50_p2 );

    SC_METHOD(thread_tmp_10_fu_184_p3);
    sensitive << ( p_Val2_5_fu_90_p2 );

    SC_METHOD(thread_tmp_11_fu_192_p3);
    sensitive << ( p_Val2_3_fu_78_p2 );

    SC_METHOD(thread_tmp_12_fu_200_p3);
    sensitive << ( p_Val2_7_fu_72_p2 );

    SC_METHOD(thread_tmp_4_fu_144_p3);
    sensitive << ( p_Val2_s_fu_132_p2 );

    SC_METHOD(thread_tmp_5_fu_152_p3);
    sensitive << ( p_Val2_1_fu_126_p2 );

    SC_METHOD(thread_tmp_6_fu_160_p3);
    sensitive << ( p_Val2_2_fu_120_p2 );

    SC_METHOD(thread_tmp_7_fu_62_p2);
    sensitive << ( inc_V );
    sensitive << ( r_V_2_fu_56_p2 );

    SC_METHOD(thread_tmp_8_fu_168_p3);
    sensitive << ( p_Val2_4_fu_108_p2 );

    SC_METHOD(thread_tmp_9_fu_176_p3);
    sensitive << ( p_Val2_6_fu_96_p2 );

    SC_METHOD(thread_tmp_fu_84_p2);
    sensitive << ( inc_V );
    sensitive << ( r_V_fu_44_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    accumulator_V_0 = "00000000000000000000000000000000";
    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "acg_top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, inc_V, "inc_V");
    sc_trace(mVcdFile, accumulator_V_0, "accumulator_V_0");
    sc_trace(mVcdFile, p_Val2_s_fu_132_p2, "p_Val2_s_fu_132_p2");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, r_V_2_fu_56_p2, "r_V_2_fu_56_p2");
    sc_trace(mVcdFile, r_V_fu_44_p2, "r_V_fu_44_p2");
    sc_trace(mVcdFile, tmp_fu_84_p2, "tmp_fu_84_p2");
    sc_trace(mVcdFile, r_V_1_fu_50_p2, "r_V_1_fu_50_p2");
    sc_trace(mVcdFile, tmp1_fu_102_p2, "tmp1_fu_102_p2");
    sc_trace(mVcdFile, tmp2_fu_114_p2, "tmp2_fu_114_p2");
    sc_trace(mVcdFile, tmp_7_fu_62_p2, "tmp_7_fu_62_p2");
    sc_trace(mVcdFile, p_Val2_1_fu_126_p2, "p_Val2_1_fu_126_p2");
    sc_trace(mVcdFile, p_Val2_2_fu_120_p2, "p_Val2_2_fu_120_p2");
    sc_trace(mVcdFile, p_Val2_4_fu_108_p2, "p_Val2_4_fu_108_p2");
    sc_trace(mVcdFile, p_Val2_6_fu_96_p2, "p_Val2_6_fu_96_p2");
    sc_trace(mVcdFile, p_Val2_5_fu_90_p2, "p_Val2_5_fu_90_p2");
    sc_trace(mVcdFile, p_Val2_3_fu_78_p2, "p_Val2_3_fu_78_p2");
    sc_trace(mVcdFile, p_Val2_7_fu_72_p2, "p_Val2_7_fu_72_p2");
    sc_trace(mVcdFile, tmp_4_fu_144_p3, "tmp_4_fu_144_p3");
    sc_trace(mVcdFile, tmp_5_fu_152_p3, "tmp_5_fu_152_p3");
    sc_trace(mVcdFile, tmp_6_fu_160_p3, "tmp_6_fu_160_p3");
    sc_trace(mVcdFile, tmp_8_fu_168_p3, "tmp_8_fu_168_p3");
    sc_trace(mVcdFile, tmp_9_fu_176_p3, "tmp_9_fu_176_p3");
    sc_trace(mVcdFile, tmp_10_fu_184_p3, "tmp_10_fu_184_p3");
    sc_trace(mVcdFile, tmp_11_fu_192_p3, "tmp_11_fu_192_p3");
    sc_trace(mVcdFile, tmp_12_fu_200_p3, "tmp_12_fu_200_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("acg_top.hdltvin.dat");
    mHdltvoutHandle.open("acg_top.hdltvout.dat");
}

acg_top::~acg_top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete acg_top_AXILiteS_s_axi_U;
}

void acg_top::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void acg_top::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        accumulator_V_0 = p_Val2_s_fu_132_p2.read();
    }
}

void acg_top::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void acg_top::thread_ap_return() {
    ap_return = esl_concat<7,1>(esl_concat<6,1>(esl_concat<5,1>(esl_concat<4,1>(esl_concat<3,1>(esl_concat<2,1>(esl_concat<1,1>(tmp_4_fu_144_p3.read(), tmp_5_fu_152_p3.read()), tmp_6_fu_160_p3.read()), tmp_8_fu_168_p3.read()), tmp_9_fu_176_p3.read()), tmp_10_fu_184_p3.read()), tmp_11_fu_192_p3.read()), tmp_12_fu_200_p3.read());
}

void acg_top::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void acg_top::thread_p_Val2_1_fu_126_p2() {
    p_Val2_1_fu_126_p2 = (!tmp_7_fu_62_p2.read().is_01() || !accumulator_V_0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_7_fu_62_p2.read()) + sc_biguint<32>(accumulator_V_0.read()));
}

void acg_top::thread_p_Val2_2_fu_120_p2() {
    p_Val2_2_fu_120_p2 = (!accumulator_V_0.read().is_01() || !tmp2_fu_114_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(accumulator_V_0.read()) + sc_biguint<32>(tmp2_fu_114_p2.read()));
}

void acg_top::thread_p_Val2_3_fu_78_p2() {
    p_Val2_3_fu_78_p2 = (!r_V_fu_44_p2.read().is_01() || !accumulator_V_0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r_V_fu_44_p2.read()) + sc_biguint<32>(accumulator_V_0.read()));
}

void acg_top::thread_p_Val2_4_fu_108_p2() {
    p_Val2_4_fu_108_p2 = (!accumulator_V_0.read().is_01() || !tmp1_fu_102_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(accumulator_V_0.read()) + sc_biguint<32>(tmp1_fu_102_p2.read()));
}

void acg_top::thread_p_Val2_5_fu_90_p2() {
    p_Val2_5_fu_90_p2 = (!accumulator_V_0.read().is_01() || !tmp_fu_84_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(accumulator_V_0.read()) + sc_biguint<32>(tmp_fu_84_p2.read()));
}

void acg_top::thread_p_Val2_6_fu_96_p2() {
    p_Val2_6_fu_96_p2 = (!r_V_1_fu_50_p2.read().is_01() || !accumulator_V_0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r_V_1_fu_50_p2.read()) + sc_biguint<32>(accumulator_V_0.read()));
}

void acg_top::thread_p_Val2_7_fu_72_p2() {
    p_Val2_7_fu_72_p2 = (!inc_V.read().is_01() || !accumulator_V_0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(inc_V.read()) + sc_biguint<32>(accumulator_V_0.read()));
}

void acg_top::thread_p_Val2_s_fu_132_p2() {
    p_Val2_s_fu_132_p2 = (!r_V_2_fu_56_p2.read().is_01() || !accumulator_V_0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r_V_2_fu_56_p2.read()) + sc_biguint<32>(accumulator_V_0.read()));
}

void acg_top::thread_r_V_1_fu_50_p2() {
    r_V_1_fu_50_p2 = (!ap_const_lv32_2.is_01())? sc_lv<32>(): inc_V.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void acg_top::thread_r_V_2_fu_56_p2() {
    r_V_2_fu_56_p2 = (!ap_const_lv32_3.is_01())? sc_lv<32>(): inc_V.read() << (unsigned short)ap_const_lv32_3.to_uint();
}

void acg_top::thread_r_V_fu_44_p2() {
    r_V_fu_44_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): inc_V.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void acg_top::thread_tmp1_fu_102_p2() {
    tmp1_fu_102_p2 = (!inc_V.read().is_01() || !r_V_1_fu_50_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(inc_V.read()) + sc_biguint<32>(r_V_1_fu_50_p2.read()));
}

void acg_top::thread_tmp2_fu_114_p2() {
    tmp2_fu_114_p2 = (!r_V_fu_44_p2.read().is_01() || !r_V_1_fu_50_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r_V_fu_44_p2.read()) + sc_biguint<32>(r_V_1_fu_50_p2.read()));
}

void acg_top::thread_tmp_10_fu_184_p3() {
    tmp_10_fu_184_p3 = p_Val2_5_fu_90_p2.read().range(31, 31);
}

void acg_top::thread_tmp_11_fu_192_p3() {
    tmp_11_fu_192_p3 = p_Val2_3_fu_78_p2.read().range(31, 31);
}

void acg_top::thread_tmp_12_fu_200_p3() {
    tmp_12_fu_200_p3 = p_Val2_7_fu_72_p2.read().range(31, 31);
}

void acg_top::thread_tmp_4_fu_144_p3() {
    tmp_4_fu_144_p3 = p_Val2_s_fu_132_p2.read().range(31, 31);
}

void acg_top::thread_tmp_5_fu_152_p3() {
    tmp_5_fu_152_p3 = p_Val2_1_fu_126_p2.read().range(31, 31);
}

void acg_top::thread_tmp_6_fu_160_p3() {
    tmp_6_fu_160_p3 = p_Val2_2_fu_120_p2.read().range(31, 31);
}

void acg_top::thread_tmp_7_fu_62_p2() {
    tmp_7_fu_62_p2 = (!r_V_2_fu_56_p2.read().is_01() || !inc_V.read().is_01())? sc_lv<32>(): (sc_biguint<32>(r_V_2_fu_56_p2.read()) - sc_biguint<32>(inc_V.read()));
}

void acg_top::thread_tmp_8_fu_168_p3() {
    tmp_8_fu_168_p3 = p_Val2_4_fu_108_p2.read().range(31, 31);
}

void acg_top::thread_tmp_9_fu_176_p3() {
    tmp_9_fu_176_p3 = p_Val2_6_fu_96_p2.read().range(31, 31);
}

void acg_top::thread_tmp_fu_84_p2() {
    tmp_fu_84_p2 = (!inc_V.read().is_01() || !r_V_fu_44_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(inc_V.read()) + sc_biguint<32>(r_V_fu_44_p2.read()));
}

void acg_top::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void acg_top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

